#!/usr/bin/env python
from rail_people_detector.closest_person_detector import ClosestPersonDetector
import rospy

log_lvls = {
   'DEBUG': rospy.DEBUG,
   'INFO': rospy.INFO,
   'WARN': rospy.WARN,
   'ERROR': rospy.ERROR,
   'FATAL': rospy.FATAL,
   'debug': rospy.DEBUG,
   'info': rospy.INFO,
   'warn': rospy.WARN,
   'error': rospy.ERROR,
   'fatal': rospy.FATAL,
}

if __name__ == "__main__":
   """
   Initialize the node
   """
   log_lvl = rospy.get_param("/logger_lvl", 'INFO')
   rospy.init_node('detector_node', log_level=log_lvls[log_lvl])
   detector = ClosestPersonDetector()
   detector.spin()
